import type { Metadata } from 'next'
import { Inter ,East_Sea_Dokdo} from 'next/font/google'
import './globals.css'
import Nav from './components/Nav'
import Footer from './components/Footer'
import Providers from './redux/Provider'
const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}:{ children: React.ReactNode}) {



  return (
    <html lang="en" className=' scroll-smooth'>
      
      <body className={inter.className}>
        <Nav/>
        <Providers>
           {children}
        </Providers>
        <Footer/>
      </body>
     
    </html>
  )
}
